
package org.adarchitecture.ws.services.user.serviciosincronizarcliente.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * Generated source version: 3.2.5
 */

@WebFault(name = "sincronizarCrmUserFault", targetNamespace = "org:adarchitecture:salesforce:user:schema:xsd:CommonAggregateComponents-2")
public class SincronizarCrmUserFault extends Exception {

    private org.adarchitecture.ws.user.canal.common.aggregate.component.FaultServiceType sincronizarCrmUserFault;

    public SincronizarCrmUserFault() {
        super();
    }

    public SincronizarCrmUserFault(String message) {
        super(message);
    }

    public SincronizarCrmUserFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SincronizarCrmUserFault(String message, org.adarchitecture.ws.user.canal.common.aggregate.component.FaultServiceType sincronizarCrmUserFault) {
        super(message);
        this.sincronizarCrmUserFault = sincronizarCrmUserFault;
    }

    public SincronizarCrmUserFault(String message, org.adarchitecture.ws.user.canal.common.aggregate.component.FaultServiceType sincronizarCrmUserFault, java.lang.Throwable cause) {
        super(message, cause);
        this.sincronizarCrmUserFault = sincronizarCrmUserFault;
    }

    public org.adarchitecture.ws.user.canal.common.aggregate.component.FaultServiceType getFaultInfo() {
        return this.sincronizarCrmUserFault;
    }
}
